#!/bin/bash
#
# /etc/init.d/serf -- startup script for serf agent
#
### BEGIN INIT INFO
# Provides:				serf
# Short-Description: 	Serf agent
# Default-Start:  		3 4 5
# Default-Stop: 		0 1 2 6
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# chkconfig: 			2345 95 20
# description: 			Serf agent
# processname: 			serf
### END INIT INFO


NAME="Serf Agent"
SERF_BINARY=/usr/local/bin/serf
SERF_AGENT_LOG=/var/log/serf/serf.log
SERF_AGENT_CONF_DIR=/usr/local/serf/

SLEEP_TIME=5
CURRENT_WAIT=0
TIMEOUT=30

start() {
    find_pid
    if [ "" = "$FOUND_PID" ]; then
      $SERF_BINARY agent -config-dir=$SERF_AGENT_CONF_DIR >>$SERF_AGENT_LOG 2>&1 &
      if [[ $? -ne 0 ]]; then
        echo "Error starting $NAME"
        exit 1
      fi
      echo "$NAME successfully started"
    else
      echo "$NAME is already running"
    fi
}

stop() {
    find_pid
    if [ -z "$FOUND_PID" ]; then
      echo "$NAME is not running, nothing to stop"
    else
      while [[ -n $FOUND_PID ]]; 
        do
        echo "Attempting to shutdown $NAME..."
        kill -INT $FOUND_PID
        if [[ $? -ne 0 ]]; then
          echo "Error stopping $NAME"
          exit 1
        fi
        sleep $SLEEP_TIME
        CURRENT_WAIT=$(($CURRENT_WAIT+$SLEEP_TIME))
        if [[ $CURRENT_WAIT -gt $TIMEOUT ]]; then
          echo "Timed out waiting for $NAME to stop"
          exit 1
        fi
        find_pid
      done
      echo "Stopped $NAME"
    fi
}

status() {
  find_pid
  if [ -z "$FOUND_PID" ]; then
    echo "$NAME is not running" ; exit 1
  else
    echo "$NAME is running : $FOUND_PID" 
  fi
}

reload() {
  find_pid
  if [ -z "$FOUND_PID" ]; then
    echo "$NAME is not running" ; exit 1
  else
    kill -HUP $FOUND_PID
    echo "Reloaded $NAME" 
  fi
}

find_pid() {
    FOUND_PID=`pgrep -f $SERF_BINARY`
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    start
  ;;
  status)
    status
  ;;
  reload)
    reload
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|reload}"
    exit 1
esac

exit 0